### ISSUE TITLE
Invalid proto descriptor for file "gnmi.proto".

### ISSUE THREAD

**Issue by miott** [CiscoTestAutomation/yang#16] opened 2020-06-10 17:42 UTC
If a library using grpcio is already installed the following error occurs when using yang.connector or yang.ncdiff.
```
2020-06-10T23:00:06: %EASYPY-ERROR: TypeError: Couldn't build proto file into descriptor pool!
2020-06-10T23:00:06: %EASYPY-ERROR: Invalid proto descriptor for file "gnmi.proto":
2020-06-10T23:00:06: %EASYPY-ERROR:   gnmi.proto: A file with this name is already in the pool.
```
The grpcio-tools library can be used to compile gNMI protobufs.  If a proto file is already compiled and installed, this error occurs.  Need a solid way to avoid this issue.

**Comment by tahigash** [comment] 2020-06-13 15:26
@miott I've found similar discussion on `protobuf` repository.

https://github.com/protocolbuffers/protobuf/issues/3002

It seems below `export` does work via ENV variable. So, this could be solution? I confirmed the error is gone after this on my env.

```
export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION='python'
```

**Comment by tahigash** [comment] 2020-10-14 20:23
@miott closing this issue since no update so far. please feel free to reopen if something we need to check on this.

**Closed by tahigash** 2020-10-14 20:23 UTC
